In [33]:
import numpy as np

In [34]:
lendint_co_data_numeric = np.loadtxt("Lending-Company-Numeric-Data.csv", delimiter=",")
lendint_co_data_numeric

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [ 2000.,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]], shape=(1043, 6))

In [35]:
lendint_co_data_numeric2 = np.genfromtxt("Lending-Company-Numeric-Data.csv", delimiter=",")
lendint_co_data_numeric2

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [ 2000.,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]], shape=(1043, 6))

In [36]:
np.array_equal(lendint_co_data_numeric, lendint_co_data_numeric2)

True

In [37]:
#When a file will not be open after setting a delimiter than we need to use the 2nd method which is np.genfromtxt("file name", delimiter = ";"...
nan_file = np.genfromtxt("Lending-Company-Numeric-Data-NAN.csv", delimiter=";")
nan_file

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [   nan,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]], shape=(1043, 6))

In [48]:
#Here we if we want to still use the loadtxt function to load a NOt a Number data than we need to use dtype = np.str_
nan_data_2 = np.loadtxt("Lending-Company-Numeric-Data-NAN.csv", delimiter=";", dtype= np.str_)
nan_data_2

array([['2000', '40', '365', '3121', '4241', '13621'],
       ['2000', '40', '365', '3061', '4171', '15041'],
       ['1000', '40', '365', '2160', '3280', '15340'],
       ...,
       ['', '40', '365', '4201', '5001', '16600'],
       ['1000', '40', '365', '2080', '3320', '15600'],
       ['2000', '40', '365', '4601', '4601', '16600']],
      shape=(1043, 6), dtype='<U5')