In [17]:
import numpy as np

In [18]:
lending_co_numaric_NAN_data = np.genfromtxt("Lending-Company-Numeric-Data-NAN.csv", delimiter=";")
lending_co_numaric_NAN_data

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [   nan,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]], shape=(1043, 6))

In [19]:
lending_co_numaric_NAN_data = np.genfromtxt("Lending-Company-Numeric-Data-NAN.csv", delimiter=";", skip_header=2)
lending_co_numaric_NAN_data

array([[ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       [ 2000.,    40.,   365.,  3041.,  4241., 15321.],
       [ 2000.,    50.,   365.,  3470.,  4820., 13720.],
       ...,
       [   nan,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]], shape=(1041, 6))

In [20]:
lending_co_numaric_NAN_data = np.genfromtxt("Lending-Company-Numeric-Data-NAN.csv", delimiter=";", skip_footer=2)
lending_co_numaric_NAN_data

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [ 2000.,    40.,   365.,  3401.,    nan, 16600.],
       [ 2000.,    40.,   365.,    nan,  5440., 16600.],
       [   nan,    40.,   365.,  4201.,  5001., 16600.]], shape=(1041, 6))

In [21]:
lending_co_numaric_NAN_data = np.genfromtxt("Lending-Company-Numeric-Data-NAN.csv", delimiter=";", usecols=(0,1,3))
lending_co_numaric_NAN_data

array([[2000.,   40., 3121.],
       [2000.,   40., 3061.],
       [1000.,   40., 2160.],
       ...,
       [  nan,   40., 4201.],
       [1000.,   40., 2080.],
       [2000.,   40., 4601.]], shape=(1043, 3))

In [22]:
lending_co_numaric_NAN_data = np.genfromtxt("Lending-Company-Numeric-Data-NAN.csv", delimiter=";", usecols=(5,2,3))
lending_co_numaric_NAN_data

array([[13621.,   365.,  3121.],
       [15041.,   365.,  3061.],
       [15340.,   365.,  2160.],
       ...,
       [16600.,   365.,  4201.],
       [15600.,   365.,  2080.],
       [16600.,   365.,  4601.]], shape=(1043, 3))

In [23]:
#All the arguments also work together . here you can see them.
lending_co_numaric_NAN_data = np.genfromtxt("Lending-Company-Numeric-Data-NAN.csv", delimiter=";", usecols=(5,2,3), skip_header=2, skip_footer=3)
lending_co_numaric_NAN_data

array([[15340.,   365.,  2160.],
       [15321.,   365.,  3041.],
       [13720.,   365.,  3470.],
       ...,
       [16600.,   365.,  3081.],
       [16600.,   365.,  3401.],
       [16600.,   365.,    nan]], shape=(1038, 3))

In [24]:
#if i want to give eac data separate column. i need to give 3 colunm namme separating with coma, and use (Unpac = True) function.
lending_co_data1, lending_co_data2, lending_co_data3 = np.genfromtxt("Lending-Company-Numeric-Data-NAN.csv", delimiter=";", usecols=(5,2,3), skip_header=2, skip_footer=3, unpack=True)
print(lending_co_data1)
print(lending_co_data2)
print(lending_co_data3)

[15340. 15321. 13720. ... 16600. 16600. 16600.]
[365. 365. 365. ... 365. 365. 365.]
[2160. 3041. 3470. ... 3081. 3401.   nan]
